"""
Constants
Constantes de la aplicación y valores de configuración
"""

# Constantes de la aplicación
APP_NAME = "Simulador de Redes Ópticas Pasivas"
APP_VERSION = "1.0.0"

# Constantes de UI
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
DEFAULT_SIDEBAR_WIDTH = 250

# Constantes de Canvas
DEFAULT_CANVAS_WIDTH = 2000
DEFAULT_CANVAS_HEIGHT = 1500
GRID_SIZE = 20

# Constantes de Nodo
DEFAULT_NODE_WIDTH = 100
DEFAULT_NODE_HEIGHT = 50
MIN_NODE_SIZE = 20
MAX_NODE_SIZE = 200

# Constantes de Línea
DEFAULT_LINE_WIDTH = 2
MIN_LINE_WIDTH = 1
MAX_LINE_WIDTH = 10

# Constantes de Dispositivos
OLT_DEFAULT_NAME = "OLT"
ONU_DEFAULT_NAME = "ONU"
MAX_ONUS_PER_OLT = 64

# Colores
PRIMARY_COLOR = "#2196F3"
SECONDARY_COLOR = "#FF9800"
SUCCESS_COLOR = "#4CAF50"
ERROR_COLOR = "#F44336"
WARNING_COLOR = "#FF9800"
